### ISSUE TITLE
Unverified App in Google OAuth

### ISSUE THREAD

**Issue by Maryse47** [mhogomchungu/qCheckGMail#41]
This app has unverified status in google OAuth API. Because of that google removed OAuth association from my account and I had to re-enable it and accept unverified status warnings. Please verify this app in google. Thank you.

[Unverified apps](https://support.google.com/cloud/answer/7454865?hl=en)
[OAuth API Verification FAQ](https://support.google.com/cloud/answer/9110914)
https://developers.google.com/apps-script/guides/client-verification

**Comment by mhogomchungu** [comment]
The verification process is proving to be much longer than i anticipated and all i seem to be doing is jumping through endless hoops.

I had a week set aside to work on it and an emergency took all the time and google denied my verification request because i missed a deadline. 

The earliest i can resume continuing with the verification process will be Monday of next week.

**Comment by mhogomchungu** [comment]
Part of the email that caused me to miss the deadline read as follows:

![Screenshot_20190819_194006](https://user-images.githubusercontent.com/3496115/63283279-7b9aed80-c2b9-11e9-9e34-70397d1ab967.png)

**Comment by Maryse47** [comment]
Thanks for your time. Those requirements sound bizarre.

**Comment by Hai-Lag** [comment]
My develop is making a translation website platform and we are almost stuck in this step! Can anyone help please?

**Comment by mhogomchungu** [comment]
The git version now works the same but without using requiring Google verification.

The project no longer need to be verified because it uses labels API[1] and these do not need to be verified.

Will make a new release soon.

[1] https://developers.google.com/gmail/api/reference/rest/v1/users.labels

**Comment by Maryse47** [comment]
Does this new api change app functionality?

**Comment by mhogomchungu** [comment]
No.

Gmail API scopes are here[1].

Previous, i was using "https://mail.google.com/" scope and this scope gives most access and requires verification with very high scrutiny. from google.

Now i am using "https://www.googleapis.com/auth/gmail.labels" scope which gives least access and does not require verification.

There is no functionality lost but also means the app can not do more than what it currently does.

The new version when it comes out will require accounts to be re-added. This is because the labels API change how labels are accessed.

The new version will not have the ability to edit existing accounts and the functionality may return later on. 

[1] https://developers.google.com/gmail/api/auth/scopes

**Comment by mhogomchungu** [comment]
```
{
  "id": "INBOX",
  "name": "INBOX",
  "messageListVisibility": "hide",
  "labelListVisibility": "labelShow",
  "type": "system",
  "messagesTotal": 10726,
  "messagesUnread": 0,
  "threadsTotal": 4102,
  "threadsUnread": 0
}
```
A response for each label look like above and the "INBOX" label is the default label in gmail where all emails go to by default. 

What the UI can show is only what is in the above output.

The reason why the account have to be re-added is because old API used label name with the new API uses label id.

**Comment by mhogomchungu** [comment]
New version of out: https://github.com/mhogomchungu/qCheckGMail/releases/tag/2.0.0
